### ISSUE TITLE
Crash loading 2.4.0 Alpha (In case no one else runs into this issue)

### ISSUE THREAD

**Issue by DarkSlayerEX** [gkbm2013/tinker-IO#30]
http://pastebin.com/dpg5nzBq

**Comment by Tsukiumy** [comment]
same here, i was going to bet it was because i was using a jenkins version from tinkers, but dont seem to be the case, i cant wait to use the new upgrade on this mod tho, for now i will just roll back till the fix :(, 

edit: seems that the crash only happens at the first start with the mod, somenthing with the timing betwen the creation of a config file and the loading of the mod

**Comment by SDUBZ** [comment]
also getting crash http://pastebin.com/63qERhjF

**Comment by gkbm2013** [comment]
I fixed the bug. Thanks for report!
https://minecraft.curseforge.com/projects/tinker-i-o/files/2349757

Details : 
https://github.com/gkbm2013/tinker-IO/commit/a13228694141af75994008e4c97087139c31efd6
