### ISSUE TITLE
cannot extract RF from Stirling Engine

### ISSUE THREAD

**Issue by s1mples** [gkbm2013/tinker-IO#91]
Having setup: StirlingEngine over TConstruct tank with lava (this part working fine - lava used up, RF genereting). EnderIO CapacitorBank right next to StirlingEngine - this part not working, no RF transfer to CapacitorBank). Trying EnderIO energy conduits on every sides of StirlingEngine - not connectiong to StirlingEngine.

forge:
forge-1.12.2-14.23.5.2806.jar

modlist:
EnderCore-1.12.2-0.5.43.jar
EnderIO-1.12.2-5.0.39.jar
Mantle-1.12-1.3.3.39.jar
RedstoneFlux-1.12-2.1.0.6-universal.jar
TConstruct-1.12.2-2.12.0.115.jar
tinker_io-1.12.2-rw2.7.1.jar

**Comment by gkbm2013** [comment]
Hello, the bug is fixed in Tinker I/O rw2.8.0. Thanks for your report!

In the old version of Tinker I/O, we use traditional RF API for the energy network. However the RF API is out-of-date. That is why most of the mods cannot extract energy from Stirling Engine. The same issue was also occurred in Ore Crusher. But for now, these issue was fixed by replacing RF API to Forge Capability API (Forge Energy API).
