### ISSUE TITLE
Cobalt oredict issue doesn't seem to be fixed

### ISSUE THREAD

**Issue by FederAndInk** [gkbm2013/tinker-IO#99]
With enderio crushing cobalt ore in the SAG mill yield ardite dust.
without tinker-io it yields cobalt dust as expected.
We can also see the oredict info of cobalt ore with tinker-io:

![Screenshot_20200428_015849](https://user-images.githubusercontent.com/24270152/80432813-9405e200-88f5-11ea-8f10-3138ce7da07b.png)

and without tinker-io:

![Screenshot_20200428_020218](https://user-images.githubusercontent.com/24270152/80432818-9a945980-88f5-11ea-9dfb-c7e73c70d488.png)

**Comment by KirikaAetheria** [comment]
I've tried fixing this issue and have added a pull request for review. in the meantime, I've compiled the fixed jar file, so if you don't feel like waiting you can download it [here](https://drive.google.com/file/d/12jjOWbn6nl1WNHRBTWZT8tEhFvz9Gt_J/view?usp=sharing) and give it a spin. I did have to delete the HWYLA dependency since their website seems to be down, but observed no issues

**Comment by gkbm2013** [comment]
The issue was solved in #100 . Thank you all for the discussion.
